import type { Request, Response } from 'express';

export default async function handler(req: Request, res: Response) {
  try {
    // In production, fetch from database
    // For now, return mock data matching your frontend
    const sdgGoals = [
      {
        id: 1,
        name: 'No Poverty',
        description: 'End poverty in all its forms everywhere',
        progress: 68,
        trend: 'up',
        status: 'on-track',
        color: 'bg-red-500',
        initiatives: 24,
        budget: '$12.5M',
        lastUpdate: '2024-12-10',
        targets: 7,
        indicators: 14,
      },
      {
        id: 2,
        name: 'Zero Hunger',
        description: 'End hunger, achieve food security',
        progress: 54,
        trend: 'down',
        status: 'needs-attention',
        color: 'bg-yellow-600',
        initiatives: 18,
        budget: '$8.2M',
        lastUpdate: '2024-12-08',
        targets: 8,
        indicators: 13,
      },
      {
        id: 3,
        name: 'Good Health and Well-being',
        description: 'Ensure healthy lives and promote well-being',
        progress: 72,
        trend: 'up',
        status: 'on-track',
        color: 'bg-green-600',
        initiatives: 31,
        budget: '$18.7M',
        lastUpdate: '2024-12-12',
        targets: 13,
        indicators: 28,
      },
      {
        id: 4,
        name: 'Quality Education',
        description: 'Ensure inclusive and equitable quality education',
        progress: 81,
        trend: 'up',
        status: 'on-track',
        color: 'bg-red-700',
        initiatives: 27,
        budget: '$15.3M',
        lastUpdate: '2024-12-11',
        targets: 10,
        indicators: 11,
      },
      {
        id: 5,
        name: 'Gender Equality',
        description: 'Achieve gender equality and empower all women',
        progress: 63,
        trend: 'stable',
        status: 'needs-attention',
        color: 'bg-orange-600',
        initiatives: 22,
        budget: '$9.8M',
        lastUpdate: '2024-12-09',
        targets: 9,
        indicators: 14,
      },
      {
        id: 6,
        name: 'Clean Water and Sanitation',
        description: 'Ensure availability and sustainable management',
        progress: 76,
        trend: 'up',
        status: 'on-track',
        color: 'bg-cyan-500',
        initiatives: 19,
        budget: '$11.2M',
        lastUpdate: '2024-12-13',
        targets: 8,
        indicators: 11,
      },
      {
        id: 7,
        name: 'Affordable and Clean Energy',
        description: 'Ensure access to affordable, reliable energy',
        progress: 58,
        trend: 'up',
        status: 'needs-attention',
        color: 'bg-yellow-500',
        initiatives: 16,
        budget: '$14.6M',
        lastUpdate: '2024-12-07',
        targets: 5,
        indicators: 6,
      },
      {
        id: 8,
        name: 'Decent Work and Economic Growth',
        description: 'Promote sustained, inclusive economic growth',
        progress: 69,
        trend: 'up',
        status: 'on-track',
        color: 'bg-purple-700',
        initiatives: 25,
        budget: '$16.4M',
        lastUpdate: '2024-12-10',
        targets: 12,
        indicators: 17,
      },
      {
        id: 9,
        name: 'Industry, Innovation and Infrastructure',
        description: 'Build resilient infrastructure',
        progress: 65,
        trend: 'up',
        status: 'on-track',
        color: 'bg-orange-700',
        initiatives: 21,
        budget: '$19.8M',
        lastUpdate: '2024-12-12',
        targets: 8,
        indicators: 12,
      },
      {
        id: 10,
        name: 'Reduced Inequalities',
        description: 'Reduce inequality within and among countries',
        progress: 52,
        trend: 'stable',
        status: 'needs-attention',
        color: 'bg-pink-600',
        initiatives: 17,
        budget: '$7.9M',
        lastUpdate: '2024-12-06',
        targets: 10,
        indicators: 11,
      },
      {
        id: 11,
        name: 'Sustainable Cities and Communities',
        description: 'Make cities inclusive, safe, resilient',
        progress: 71,
        trend: 'up',
        status: 'on-track',
        color: 'bg-yellow-700',
        initiatives: 23,
        budget: '$13.5M',
        lastUpdate: '2024-12-11',
        targets: 10,
        indicators: 15,
      },
      {
        id: 12,
        name: 'Responsible Consumption and Production',
        description: 'Ensure sustainable consumption patterns',
        progress: 59,
        trend: 'up',
        status: 'needs-attention',
        color: 'bg-amber-700',
        initiatives: 15,
        budget: '$8.7M',
        lastUpdate: '2024-12-09',
        targets: 11,
        indicators: 13,
      },
      {
        id: 13,
        name: 'Climate Action',
        description: 'Take urgent action to combat climate change',
        progress: 61,
        trend: 'up',
        status: 'needs-attention',
        color: 'bg-green-700',
        initiatives: 28,
        budget: '$21.3M',
        lastUpdate: '2024-12-14',
        targets: 5,
        indicators: 8,
      },
      {
        id: 14,
        name: 'Life Below Water',
        description: 'Conserve and sustainably use the oceans',
        progress: 48,
        trend: 'down',
        status: 'critical',
        color: 'bg-blue-600',
        initiatives: 12,
        budget: '$6.4M',
        lastUpdate: '2024-12-05',
        targets: 10,
        indicators: 10,
      },
      {
        id: 15,
        name: 'Life on Land',
        description: 'Protect, restore and promote sustainable use',
        progress: 55,
        trend: 'stable',
        status: 'needs-attention',
        color: 'bg-green-600',
        initiatives: 19,
        budget: '$9.1M',
        lastUpdate: '2024-12-08',
        targets: 12,
        indicators: 14,
      },
      {
        id: 16,
        name: 'Peace, Justice and Strong Institutions',
        description: 'Promote peaceful and inclusive societies',
        progress: 67,
        trend: 'up',
        status: 'on-track',
        color: 'bg-blue-800',
        initiatives: 20,
        budget: '$10.6M',
        lastUpdate: '2024-12-10',
        targets: 12,
        indicators: 23,
      },
      {
        id: 17,
        name: 'Partnerships for the Goals',
        description: 'Strengthen means of implementation',
        progress: 74,
        trend: 'up',
        status: 'on-track',
        color: 'bg-indigo-800',
        initiatives: 26,
        budget: '$12.9M',
        lastUpdate: '2024-12-13',
        targets: 19,
        indicators: 25,
      },
    ];

    return res.status(200).json({
      success: true,
      data: sdgGoals,
      count: sdgGoals.length,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Get SDG goals error:', error);
    return res.status(500).json({
      success: false,
      error: 'Internal server error',
      message: String(error),
    });
  }
}
